{% set name = "sunkit-instruments" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2fb5707c4ded18044888e05f9be80ffff3c83265716b2c2f032e5e4c172266d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - sunpy >=5.0.0
    - pandas
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - astropy

test:
  requires:
    - pytest-astropy
    - pytest-doctestplus
    - pytest-mock
  imports:
    - sunkit_instruments
    - sunkit_instruments.fermi
    - sunkit_instruments.goes_xrs
    - sunkit_instruments.iris
    - sunkit_instruments.lyra
    - sunkit_instruments.rhessi
  commands:
    - python -m pytest -vvv --pyargs sunkit_instruments

about:
  home: https://github.com/sunpy/sunkit-instruments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A SunPy-affiliated package for solar instrument-specific tools.
  description: |
    A SunPy-affiliated package for solar instrument-specific tools.
  doc_url: https://sunkit-instruments.readthedocs.io/en/latest/
  dev_url: https://github.com/sunpy/sunkit-instruments

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
    - wtbarnes
