{% set name = "sunkit-instruments" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ec19a60bb39da41757bc756b64d9c6cec7aa8b8bb27df94b69c216ada3ade3c1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - sunpy >=4.0.0

test:
  requires:
    - pytest-astropy
    - pytest-doctestplus
    - pytest-mock
  imports:
    - sunkit_instruments
    - sunkit_instruments.fermi
    - sunkit_instruments.goes_xrs
    - sunkit_instruments.iris
    - sunkit_instruments.lyra
    - sunkit_instruments.rhessi
  commands:
    - python -m pytest -vvv --pyargs sunkit_instruments

about:
  home: https://github.com/sunpy/sunkit-instruments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A SunPy-affiliated package for solar instrument-specific tools.
  description: |
    A SunPy-affiliated package for solar instrument-specific tools.
  doc_url: https://sunkit-instruments.readthedocs.io/en/latest/
  dev_url: https://github.com/sunpy/sunkit-instruments

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
