{% set name = "sunkit-instruments" %}
{% set version = "0.6.2" %}
{% set python_min = "3.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 042362eaddb87ef25a6689d86a0f2b2dbf174597cc08b53ff626546634e665b1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - sunpy >=6.0.0
    - xarray >=2023.12.0
    - astropy-base >=5.3.0
    - packaging >=23.0
    - scipy >=1.9.0,!=1.10.0
    - numpy >=1.23.5
    - h5py >=3.7.0
    - matplotlib-base >=3.6.0
    - pandas >=1.4.0

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-astropy
    - pytest-doctestplus
    - pytest-mock
  imports:
    - sunkit_instruments
    - sunkit_instruments.fermi
    - sunkit_instruments.goes_xrs
    - sunkit_instruments.iris
    - sunkit_instruments.lyra
    - sunkit_instruments.rhessi
  commands:
    - python -m pytest -vvv --pyargs sunkit_instruments

about:
  home: https://github.com/sunpy/sunkit-instruments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A SunPy-affiliated package for solar instrument-specific tools.
  description: |
    A SunPy-affiliated package for solar instrument-specific tools.
  doc_url: https://sunkit-instruments.readthedocs.io/en/latest/
  dev_url: https://github.com/sunpy/sunkit-instruments

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
    - wtbarnes
