{% set name = "sunkit-instruments" %}
{% set version = "0.6.0" %}
{% set python_min = "3.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2178e881f2ae2970b8618325cca3528f7cba2d9c4f71966dbbab5a8f8aee4054

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - sunpy >=6.0.0
    - pandas
    - numpy
    - scipy
    - matplotlib-base
    - h5py
    - astropy-base

test:
  requires:
    - python {{ python_min }}
    - pytest-astropy
    - pytest-doctestplus
    - pytest-mock
  imports:
    - sunkit_instruments
    - sunkit_instruments.fermi
    - sunkit_instruments.goes_xrs
    - sunkit_instruments.iris
    - sunkit_instruments.lyra
    - sunkit_instruments.rhessi
  commands:
    - python -m pytest -vvv --pyargs sunkit_instruments

about:
  home: https://github.com/sunpy/sunkit-instruments
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A SunPy-affiliated package for solar instrument-specific tools.
  description: |
    A SunPy-affiliated package for solar instrument-specific tools.
  doc_url: https://sunkit-instruments.readthedocs.io/en/latest/
  dev_url: https://github.com/sunpy/sunkit-instruments

extra:
  recipe-maintainers:
    - cadair
    - nabobalis
    - wtbarnes
